<h1>Books</h1>

<p><a href="<?php echo $this->url('home/crud', array('action' => 'add'))?>">Add new book</a></p>

<?php if (count($this->books) > 0) { ?>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Book title</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->books as $book) {?>
        <tr>
            <td><?php echo $book->getId()?></td>
            <td><a href="<?php echo $this->url('home/crud', array('action' => 'edit', 'id' => $book->getId()))?>"><?php echo $book->getTitle()?></a></td>
            <td><a class="btn btn-small" href="<?php echo $this->url('home/crud', array('action' => 'remove', 'id' => $book->getId()))?>"><i class="icon-trash"></i> Remove</a></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php } ?>